AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Provisions a demo stack with webpacked dependencies

Resources:
  # lambdas
  myHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-myHandler'
      Handler: index.handler
      CodeUri: dist/myHandler
      Runtime: nodejs16.x
      Timeout: 6
      MemorySize: 128
